# Generated by Django 4.0.3 on 2022-04-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
