# Generated by Django 4.0.3 on 2022-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedIn_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
