# Generated by Django 4.0.3 on 2022-04-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='content_rate',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='design_rate',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='usability_rate',
            new_name='usability',
        ),
    ]
